# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [68]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [69]:
A = np.arange(1, 16).reshape(3,5)

In [70]:
print(f'''Dimensions: {A.ndim}
Shape: {A.shape}
Size: { A.size}
Datatype: {A.dtype}''')

Dimensions: 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [71]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [72]:
B-C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [73]:
B*C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [74]:
B@C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [75]:
B = np.arange(1, 10).reshape(3, 3)

# Prettier floats
with np.printoptions(precision=2, suppress=True):
    print(f'''
Exponentiate: 
{np.exp(B)}
Minimum value (matrix): {B.min()}
Minimum values (rows): {B.min(axis=1)}
Minimum values (columns): {B.min(axis=0)}
Index of minimum value (matrix): {B.argmin()}
    B.flat[B.argmin()] == {B.flat[B.argmin()]}
Index of minimum value (rows): {B.argmin(axis=1)}
Sum of all elements: {B.sum()}
Mean of each column: {B.mean(axis=0)}
Median of each column: {np.median(B, axis=0)}
        ''')


Exponentiate: 
[[   2.72    7.39   20.09]
 [  54.6   148.41  403.43]
 [1096.63 2980.96 8103.08]]
Minimum value (matrix): 1
Minimum values (rows): [1 4 7]
Minimum values (columns): [1 2 3]
Index of minimum value (matrix): 0
    B.flat[B.argmin()] == 1
Index of minimum value (rows): [0 0 0]
Sum of all elements: 45
Mean of each column: [4. 5. 6.]
Median of each column: [4. 5. 6.]
        


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [76]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [77]:
A[...,2] == A[:, 2]

array([ True,  True,  True])

**Answer:**
The omitted indices are converted to complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [78]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [79]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [80]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [81]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)
b.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


(2, 3, 5)

It means that `b` consists of 2 stacked 3 &times; 5 arrays, it has 3 dimensions. 

The -1 argument to `reshape` tells numpy to figure out the best shape based on the two first arguments.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [82]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [83]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [84]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [85]:
A = np.array([
    [2, 1, -1], 
    [1, -1, 1]
    ])

B = np.array([
    [4, -2, 1], 
    [2, -4, -2]
    ])

C = np.array([
    [1, 2], 
    [2, 1]
    ])

D = np.array([
    [3, 4], 
    [4, 3],
    [2, 4]
    ])

E = np.array([
    [1], 
    [2]
    ])
     
F = [
    [1, 2, 4], 
    [2, 2, 3], 
    [1, 5, 7]
    ]

G = np.array([
    [1, 2], 
    [8, 6], 
    [5, 4]]
    )

**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [86]:

def add_mult_matrices(A, B, mode=None):
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise TypeError('Matrices must be numpy arrays.')
    if mode not in ('add', 'multiply'):
        raise ValueError('You must specify add or multiply')
    if mode == 'add':
        if A.shape == B.shape:
            return A + B
        else:
            raise AttributeError('Matrices must have same shape')
    elif mode == 'multiply':
        if A.shape[1] == B.shape[0]:
            return A @ B
        else:
            raise AttributeError('Shape mismatch')


In [87]:
# Testing add_mult_matrices function

import pytest
def test_add_mult():
    assert np.allclose(add_mult_matrices(A, B, mode='add'), np.array([[ 6, -1,  0], [ 3, -5, -1]]))
    
    assert np.allclose(add_mult_matrices(A, D, mode='multiply'), np.array([[8, 7], [1, 5]]))

    with pytest.raises(ValueError):
        add_mult_matrices(A, D, mode='subtract')  # <-- raises Exception
        
    with pytest.raises(AttributeError):
        add_mult_matrices(A, D, mode='add') # <-- raises Exception
        
    with pytest.raises(TypeError):
        add_mult_matrices(B, F, mode='multiply') # <-- raises Exception

test_add_mult()


**Chap2. Question 2**

In [88]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

assert AB.all() == AC.all() and B.all() != C.all()

**Chap2. Question 3**

In [89]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = add_mult_matrices(A, D, 'multiply')
DA = add_mult_matrices(D, A, 'multiply')
AD, DA

(array([[ 2,  3,  4],
        [ 2,  6, 12],
        [ 2,  9, 16]]),
 array([[ 2,  2,  2],
        [ 3,  6,  9],
        [ 4, 12, 16]]))

**Quiz p.11, Question 2**

In [90]:
add_mult_matrices(np.array([[1, -1], [-1, 1]]), np.array([[-1, 1], [1, -1]]), 'multiply')


array([[-2,  2],
       [ 2, -2]])

**Chap 6. Question 1**

In [91]:
I = np.identity(2)

A = np.array([[5, 6], [4, 5]])
Ai = np.linalg.inv(A)
(A@Ai).all() == I.all()

B = np.array([[6, 4], [3, 3]])
Bi = np.linalg.inv(B)
(B@Bi).all() == I.all()

I.T@I

array([[1., 0.],
       [0., 1.]])

**Quiz p.19, Question 3**

In [92]:
A = np.array([[2, 2], [1, 2]])
np.linalg.inv(A)

array([[ 1. , -1. ],
       [-0.5,  1. ]])

**Chap10. Question 1 a)**

In [93]:
A = np.array([[3, -7, -2], 
              [-3, 5, 1], 
              [6, -4, 0]])
b = np.array([-7, 5, 2])
x = np.linalg.solve(A, b)
x

array([ 3.,  4., -6.])

**Chap10. Question 1 b)**

In [94]:
A = np.array([[1, -2, 3], 
              [-1, 3, -1], 
              [2, -5, 5]])
b = np.array([1, -1, 1])
x = np.linalg.solve(A, b)
x

array([ 8.,  2., -1.])

**Chap 12. Question 1**

In [95]:
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])
np.linalg.inv(A)

array([[ 0.67,  1.33,  0.5 ],
       [ 1.  ,  2.  ,  0.5 ],
       [-3.  , -5.  , -1.  ]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [96]:
v1 = np.arange(4)
v2 = v1[-2:]
print('v1: ' + ('View' if v1.base is not None else 'Copy'))
print('v2: ' + ('View' if v2.base is not None else 'Copy'))
v2[-1] = 123
v1

v1: Copy
v2: View


array([  0,   1,   2, 123])

**Answer**

v2 is a view and so is 'connected' to the original array. Any changes made to either of v1 and v2 reflects in the other.

In [97]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [98]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
